name: Fly Production Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - Dockerfile
      - fly.toml
      - pyproject.toml
      - uv.lock
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}